### ISSUE TITLE
Discussion: Can we imagine a "@embedded" like HAL "_embedded" ?

### ISSUE THREAD

**Issue by schidaine** [JornWildt/Mason#19]
Hi,
looking for a hypermedia notation, MASON is one of my two favourites. The other is HAL just because of "_embedded" structure which is relevant for mobile applications.
I would propose a "@embedded" for the same purpose in MASON.

Regards,
Sylvain

**Comment by JornWildt** [comment]
There has been a lot of misunderstandings and questions about the exact sematics of embedded elements. I would rather avoid those issues which is why I have not included some sort of embedded element in Mason. So, sorry, but no, @embedded is not going into Mason.

But of course, you are free to specify an embedded feature that works for your setup and document that as part of your API.
